In [2]:
#  Lab-01-1 Tensor Manipulation 2
import numpy as np
import torch

t = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [5]:
print(ft.view([-1,3])) 
print(ft.view([-1,3]).shape) # numpy -> reshape

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [6]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [10]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [12]:
print(ft.squeeze()) # view랑 비슷하지만, 자동으로 원하는 dim에 또는 전체에서 하나만 남아있는 경우에 그 dim을 없애줌(Size(3,1)인 경우 뒤에꺼)
print(ft.squeeze().shape) # squeeze(dim=?)으로 하면 해당 dim이 1일 경우 선택적으로 없애게 할 수 있음

tensor([0., 1., 2.])
torch.Size([3])


In [16]:
ft = torch.Tensor([0,1,2])
print(ft.shape)
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [18]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)  

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [19]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [20]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape) # numpy.shape -> tuple, torch.size() -> torch.Size라는 object로 나옴 / torch.shape이랑 동일하게 출력

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [29]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [33]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [35]:
bt = torch.ByteTensor([True,False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [37]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [38]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])
print(torch.cat([x,y], dim=0))
print(torch.cat([x,y], dim=1))




tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])
