In [2]:
#  Lab-01-1 Tensor Manipulation 2
import numpy as np
import torch

t = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


/home/paul/mambaforge/envs/qtc/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
print(ft.view([-1,3])) 
print(ft.view([-1,3]).shape) # numpy -> reshape

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [4]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [5]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [6]:
print(ft.squeeze()) # view랑 비슷하지만, 자동으로 원하는 dim에 또는 전체에서 하나만 남아있는 경우에 그 dim을 없애줌(Size(3,1)인 경우 뒤에꺼)
print(ft.squeeze().shape) # squeeze(dim=?)으로 하면 해당 dim이 1일 경우 선택적으로 없애게 할 수 있음

tensor([0., 1., 2.])
torch.Size([3])


In [7]:
ft = torch.Tensor([0,1,2])
print(ft.shape)
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [8]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)  

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [9]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [10]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape) # numpy.shape -> tuple, torch.size() -> torch.Size라는 object로 나옴 / torch.shape이랑 동일하게 출력

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [11]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [12]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [13]:
bt = torch.ByteTensor([True,False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [14]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [15]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])
print(torch.cat([x,y], dim=0)) # dim 방향으로 늘어난다고 생각하면 됨
print(torch.cat([x,y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [20]:
x =torch.FloatTensor([1,4]) # concatenate를 좀 더 편리하게 만든 기능
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])
print(torch.stack([x,y,z])) # Tensor들을 담고 있는 list를 쌓으라는 말
print(torch.stack([x,y,z], dim=1)) # dim방향으로 늘어남

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [24]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0).shape)

torch.Size([3, 2])
