#### 3.2.1 From Python lists to PyTorch tensors

In [2]:
import torch
a = [1.0, 2.0, 1.0]

/home/paul/mambaforge/envs/qtc/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
a[0]
a[2] = 3.0
a[2]
a

[1.0, 2.0, 3.0]

#### Constructing our first tensors

In [4]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [5]:
a[1]

tensor(1.)

In [6]:
float(a[1])

1.0

In [7]:
a[2] = 2.0
a

tensor([1., 1., 2.])

#### 3.2.3 The essence of tensors

In [8]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points


tensor([4., 1., 5., 3., 2., 1.])

In [9]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [10]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [11]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [12]:
points.shape

torch.Size([3, 2])

In [13]:
points = torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [14]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points[0,1]

tensor(1.)

In [15]:
points[0]

tensor([4., 1.])

#### 3.3 Indexing Tensor

In [16]:
some_list = list(range(6))
some_list[:]
some_list[1:4]
some_list[1:]
some_list[:-1]
some_list[1:4:2]

[1, 3]

In [17]:
points[1:]
points[1:,:]
points[1:,0]
points[None] 

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

#### 3.4 Named tensors

In [18]:
img_t = torch.randn(3,5,5) # shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])
img_t

tensor([[[ 0.2186, -0.2975, -1.4101,  0.8560, -0.8600],
         [ 0.3392,  1.4222, -0.6168,  0.1968, -1.7776],
         [ 0.1940,  0.3128,  1.6745,  1.0437, -1.5963],
         [ 1.6463,  1.2363,  0.2480,  0.7715,  0.4904],
         [ 0.0429, -1.4836,  1.4564,  0.7844,  0.8058]],

        [[-0.0831, -1.4306,  0.0875,  0.0878, -0.1873],
         [-0.5197, -0.7889,  0.9453,  0.2616, -0.3907],
         [-1.0969, -0.8747,  1.2425,  0.4082,  1.7663],
         [-0.6740, -0.2710, -0.1148, -0.4517, -1.6634],
         [ 2.9339,  1.3448,  0.1918, -0.0867, -0.5596]],

        [[ 0.4611,  1.6779, -0.0590,  0.1882,  0.5097],
         [-1.1940,  1.2036, -1.0152, -0.1147,  0.2017],
         [ 1.5020,  1.5482, -0.6225, -1.9493, -0.6928],
         [-1.2223, -0.2460,  0.0812, -0.4427,  0.1257],
         [ 0.5773, -0.5746,  0.5498,  0.9008, -0.9610]]])

In [19]:
batch_t = torch.randn(2, 3, 5, 5)

In [33]:
img_gray_naive = img_t.mean(-3) # ()안에 숫자는 .size()의 Index위치를 나타냄. negative indexing이 가능함. 보통은 -1만 씀.
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [38]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t*unsqueezed_weights)
batch_weights = (batch_t*unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
print(img_t.shape, weights.shape, unsqueezed_weights.shape)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape, img_weights.shape

torch.Size([3, 5, 5]) torch.Size([3]) torch.Size([3, 1, 1])


(torch.Size([2, 3, 5, 5]),
 torch.Size([2, 3, 5, 5]),
 torch.Size([3, 1, 1]),
 torch.Size([3, 5, 5]))

#### unsqueeze example

In [25]:
a = torch.tensor([[1, 2], [3, 4], [5, 6]])
b = torch.tensor([1, 1])
print(a.size(), b.size())
a+b

torch.Size([3, 2]) torch.Size([2])


tensor([[2, 3],
        [4, 5],
        [6, 7]])

In [26]:
a = torch.tensor([[1, 3, 5], [2, 4, 6]])
b = torch.tensor([1, 1])
print(a.size(), b.size())
a+b

torch.Size([2, 3]) torch.Size([2])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [27]:
a = torch.tensor([[1, 3, 5], [2, 4, 6]])
b = torch.tensor([1, 1]).unsqueeze(-1)
print(b)
print(a.size(), b.size())
a+b

tensor([[1],
        [1]])
torch.Size([2, 3]) torch.Size([2, 1])


tensor([[2, 4, 6],
        [3, 5, 7]])

In [48]:
print(img_t.shape, weights.shape, batch_t.shape)
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
batch_t, weights, batch_gray_weighted_fancy

torch.Size([3, 5, 5]) torch.Size([3]) torch.Size([2, 3, 5, 5])


(tensor([[[[ 0.3845, -1.1025,  0.5564,  0.5431, -0.1063],
           [-0.6325,  0.4164, -0.4063,  0.4241,  0.7437],
           [ 0.0489, -0.7385,  1.4587,  0.7679,  1.0362],
           [-0.1793, -1.9656,  0.1711,  1.8167,  0.4754],
           [ 1.3298, -0.5517, -1.0594, -1.4008, -1.1963]],
 
          [[-1.0382, -1.3235,  0.6334,  0.0487, -1.4143],
           [ 1.4939,  0.1094, -0.3771,  1.0141, -0.2653],
           [-0.8385, -2.7776,  0.3090,  0.5571, -1.1236],
           [ 1.1892,  1.1327, -1.3428,  0.7328, -0.1831],
           [-1.6401, -1.0479, -0.4189, -1.4258,  0.7155]],
 
          [[-1.5731, -0.7965,  1.5081,  0.1891, -1.4752],
           [-0.2894, -0.2603, -0.3767, -0.6214, -0.7118],
           [ 0.7494,  0.4127, -1.6566,  0.0103,  0.0305],
           [-0.3892,  0.0955,  0.7855, -0.6072,  0.7304],
           [-1.4054, -1.0455, -2.1222, -0.7565,  0.3038]]],
 
 
         [[[-2.7866,  0.9065,  0.8948,  0.2816,  1.3638],
           [-1.7164,  1.7750, -0.0635,  0.4487, -0.7344],
  

In [49]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

/tmp/ipykernel_477/2371314847.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at /home/conda/feedstock_root/build_artifacts/pytorch-recipe_1673730874951/work/c10/core/TensorImpl.h:1758.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [50]:
img_named = img_t.refine_names(...,'channels','rows','column')
batch_named = batch_t.refine_names(...,'channels','rows','column')
print("img named: ", img_named.shape, img_named.names)
print("batch named: ", batch_named.shape, batch_named.names)

img named:  torch.Size([3, 5, 5]) ('channels', 'rows', 'column')
batch named:  torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'column')


In [52]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'column'))