#### 3.2.1 From Python lists to PyTorch tensors

In [1]:
import torch
a = [1.0, 2.0, 1.0]

/Users/paul/opt/miniconda3/envs/qtc/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
a[0]
a[2] = 3.0
a[2]
a

[1.0, 2.0, 3.0]

#### Constructing our first tensors

In [3]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [4]:
a[1]

tensor(1.)

In [5]:
float(a[1])

1.0

In [6]:
a[2] = 2.0
a

tensor([1., 1., 2.])

#### 3.2.3 The essence of tensors

In [7]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points


tensor([4., 1., 5., 3., 2., 1.])

In [8]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [9]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [10]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [11]:
points.shape

torch.Size([3, 2])

In [12]:
points = torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [13]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points[0,1]

tensor(1.)

In [14]:
points[0]

tensor([4., 1.])

#### 3.3 Indexing Tensor

In [15]:
some_list = list(range(6))
some_list[:]
some_list[1:4]
some_list[1:]
some_list[:-1]
some_list[1:4:2]

[1, 3]

In [16]:
points[1:]
points[1:,:]
points[1:,0]
points[None] 

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

#### 3.4 Named tensors

In [17]:
img_t = torch.randn(3,5,5) # shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])
img_t

tensor([[[-0.7938,  0.6075,  0.9082,  0.4241,  2.2572],
         [-0.8217,  0.4987, -0.0948,  1.0067, -0.4655],
         [ 0.3190,  1.0046, -0.5981, -0.1966,  1.5389],
         [ 0.2672,  0.5282, -1.6886,  0.3451, -1.1807],
         [ 0.2916,  1.1839, -1.4662,  1.1264, -1.1599]],

        [[-0.1817, -0.2853,  0.1442, -0.9643,  1.0890],
         [ 0.4344,  0.2009,  0.5308, -0.9848, -1.3542],
         [ 1.0477,  1.2237, -0.5820,  1.2197,  0.9340],
         [ 0.6360, -1.1807,  1.0356,  0.2587,  0.0816],
         [-0.5641,  0.1976, -1.2551,  1.9304, -2.3320]],

        [[ 0.2006, -1.7610, -0.1867, -1.4708,  1.2231],
         [-0.5939,  1.5249, -0.3881,  1.4355,  0.1178],
         [-0.4833, -0.7895, -0.0149, -0.9326,  1.2126],
         [-0.4570, -0.4582, -2.2897,  1.5273, -1.3202],
         [-0.7859,  0.1795, -0.3935,  0.2754, -2.5857]]])

In [18]:
batch_t = torch.randn(2, 3, 5, 5)

In [19]:
img_gray_naive = img_t.mean(-3) # ()안에 숫자는 .size()의 Index위치를 나타냄. negative indexing이 가능함. 보통은 -1만 씀.
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [20]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t*unsqueezed_weights)
batch_weights = (batch_t*unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
print(img_t.shape, weights.shape, unsqueezed_weights.shape)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape, img_weights.shape

torch.Size([3, 5, 5]) torch.Size([3]) torch.Size([3, 1, 1])


(torch.Size([2, 3, 5, 5]),
 torch.Size([2, 3, 5, 5]),
 torch.Size([3, 1, 1]),
 torch.Size([3, 5, 5]))

#### unsqueeze example

In [21]:
a = torch.tensor([[1, 2], [3, 4], [5, 6]])
b = torch.tensor([1, 1])
print(a.size(), b.size())
a+b

torch.Size([3, 2]) torch.Size([2])


tensor([[2, 3],
        [4, 5],
        [6, 7]])

In [22]:
a = torch.tensor([[1, 3, 5], [2, 4, 6]])
b = torch.tensor([1, 1])
print(a.size(), b.size())
a+b

torch.Size([2, 3]) torch.Size([2])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [ ]:
a = torch.tensor([[1, 3, 5], [2, 4, 6]])
b = torch.tensor([1, 1]).unsqueeze(-1)
print(b)
print(a.size(), b.size())
a+b

tensor([[1],
        [1]])
torch.Size([2, 3]) torch.Size([2, 1])


tensor([[2, 4, 6],
        [3, 5, 7]])

In [ ]:
print(img_t.shape, weights.shape, batch_t.shape)
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
batch_t, weights, batch_gray_weighted_fancy

torch.Size([3, 5, 5]) torch.Size([3]) torch.Size([2, 3, 5, 5])


(tensor([[[[ 0.3845, -1.1025,  0.5564,  0.5431, -0.1063],
           [-0.6325,  0.4164, -0.4063,  0.4241,  0.7437],
           [ 0.0489, -0.7385,  1.4587,  0.7679,  1.0362],
           [-0.1793, -1.9656,  0.1711,  1.8167,  0.4754],
           [ 1.3298, -0.5517, -1.0594, -1.4008, -1.1963]],
 
          [[-1.0382, -1.3235,  0.6334,  0.0487, -1.4143],
           [ 1.4939,  0.1094, -0.3771,  1.0141, -0.2653],
           [-0.8385, -2.7776,  0.3090,  0.5571, -1.1236],
           [ 1.1892,  1.1327, -1.3428,  0.7328, -0.1831],
           [-1.6401, -1.0479, -0.4189, -1.4258,  0.7155]],
 
          [[-1.5731, -0.7965,  1.5081,  0.1891, -1.4752],
           [-0.2894, -0.2603, -0.3767, -0.6214, -0.7118],
           [ 0.7494,  0.4127, -1.6566,  0.0103,  0.0305],
           [-0.3892,  0.0955,  0.7855, -0.6072,  0.7304],
           [-1.4054, -1.0455, -2.1222, -0.7565,  0.3038]]],
 
 
         [[[-2.7866,  0.9065,  0.8948,  0.2816,  1.3638],
           [-1.7164,  1.7750, -0.0635,  0.4487, -0.7344],
  

In [26]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [27]:
img_named = img_t.refine_names(...,'channels','rows','column')
batch_named = batch_t.refine_names(...,'channels','rows','column')
print("img named: ", img_named.shape, img_named.names)
print("batch named: ", batch_named.shape, batch_named.names)

img named:  torch.Size([3, 5, 5]) ('channels', 'rows', 'column')
batch named:  torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'column')


In [28]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'column'))

In [33]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'column'))

In [34]:
gray_named = (img_named[..., :3]*weights_named).sum('channels')

RuntimeError: Error when attempting to broadcast dims ['channels', 'rows', 'column'] and dims ['channels']: dim 'column' and dim 'channels' are at the same position from the right but do not match.

In [35]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

#### 3.5.3 Managing a tensor's dtype attribute

In [37]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [38]:
short_points.dtype

torch.int16

In [40]:
double_points = torch.zeros(10,2).double()
short_points = torch.ones(10,2).short()

In [41]:
double_points = torch.zeros(10,2).to(torch.double)
short_points = torch.ones(10,2).to(dtype=torch.short)

In [42]:
points_64 = torch.rand(5, dtype=torch.double)
points_short = points_64.to(torch.short)
points_64 * points_short # works form PyTorch 1.3 onwards

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

#### 3.6 The tensor API

In [45]:
a = torch.ones(3,2)
a_t = torch.transpose(a, 0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [47]:
a = torch.ones(3,2)
a_t = a.transpose(0,1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

#### 3.7.1 Indexing into storage

In [48]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [49]:
points_storage = points.storage()
points_storage[0]

4.0

In [51]:
points.storage()[1]

1.0

In [52]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

#### 3.7.2 Modifying stored values : In-place operations

In [53]:
a = torch.ones(3,2)
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

#### 3.8 Tensor metadata : Size, offset, and stride

#### 3.8.1 Views of another tensor's storage

In [67]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1] # points.storage를 그대로 가져와서 offset이 바뀜
second_point.storage_offset()

2

In [68]:
second_point.size()

torch.Size([2])

In [69]:
second_point.shape

torch.Size([2])

In [70]:
points.stride()

(2, 1)

In [71]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [73]:
second_point.storage_offset()

2

In [77]:
second_point.stride()

(1,)

In [78]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1] # points.storage를 그대로 가져와서 offset이 바뀜
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [79]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

#### 3.8.2 Transposing without copying

In [80]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [82]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [83]:
id(points.storage()) == id(points_t.storage())

True

In [84]:
points.stride()

(2, 1)

In [86]:
points_t.stride()

(1, 2)

#### 3.8.3 Transposing in higher dimensions

In [88]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [90]:
transpose_t.shape

torch.Size([5, 4, 3])

In [93]:
some_t.stride()

(20, 5, 1)

In [94]:
transpose_t.stride()

(1, 5, 20)

#### 3.8.4 Contiguous tensors

In [96]:
points.is_contiguous()

True

In [97]:
points_t.is_contiguous()

False

In [99]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [100]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [101]:
points_t.stride()

(1, 2)

In [107]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [105]:
points_t_cont.stride()

(3, 1)

In [109]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]