#### 3.2.1 From Python lists to PyTorch tensors

In [2]:
import torch
a = [1.0, 2.0, 1.0]

In [8]:
a[0]
a[2] = 3.0
a[2]
a

[1.0, 2.0, 3.0]

#### Constructing our first tensors

In [14]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [15]:
a[1]

tensor(1.)

In [17]:
float(a[1])

1.0

In [20]:
a[2] = 2.0
a

tensor([1., 1., 2.])

#### 3.2.3 The essence of tensors

In [23]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points


tensor([4., 1., 5., 3., 2., 1.])

In [24]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [27]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [28]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [29]:
points.shape

torch.Size([3, 2])

In [32]:
points = torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [33]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points[0,1]

tensor(1.)

In [34]:
points[0]

tensor([4., 1.])

#### 3.3 Indexing Tensor

In [50]:
some_list = list(range(6))
some_list[:]
some_list[1:4]
some_list[1:]
some_list[:-1]
some_list[1:4:2]

[1, 3]

In [56]:
points[1:]
points[1:,:]
points[1:,0]
points[None] 

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

#### 3.4 Named tensors

In [68]:
img_t = torch.randn(3,5,5) # shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])
img_t

tensor([[[ 0.6322, -0.5656,  0.2024, -0.8776, -0.2098],
         [-1.8268, -0.8488, -3.3516,  0.4154, -0.3065],
         [ 0.6069,  0.2908,  0.7466,  0.1745, -1.2304],
         [ 2.1798,  2.0832,  0.0914,  2.1204, -0.2630],
         [-0.5659, -0.6019,  0.9852,  1.2570, -1.0116]],

        [[ 1.1560, -0.3889, -0.1552,  1.8253, -1.3886],
         [ 0.5546,  1.0211,  0.7299, -0.6069, -0.2443],
         [-0.8529, -1.4834, -0.6923, -0.1683, -0.4389],
         [ 0.3704,  1.3028, -0.1395, -0.6244, -1.4982],
         [-0.2415, -0.3498,  0.2903, -0.7878,  0.2743]],

        [[ 0.8095,  0.9049, -0.7616, -0.3768,  0.0737],
         [-1.1673,  0.2119,  0.3719,  0.4346, -0.6394],
         [ 0.1020,  0.7570,  0.6370,  0.5251,  0.3447],
         [-0.1364,  0.8966, -2.1693, -1.7510,  0.2114],
         [-0.1477, -1.9529, -0.4617,  0.1703,  1.9427]]])

In [59]:
batch_t = torch.randn(2, 3, 5, 5)

In [67]:
img_gray_naive = img_t.mean(-3) # ()안에 숫자는 .size()의 Index위치를 나타냄. negative indexing이 가능함. 보통은 -1만 씀.
img_gray_naive

tensor([[-0.1640, -0.4979,  0.6942, -0.3719, -0.2050],
        [ 0.6882,  0.1505,  0.1878, -0.0644, -0.1099],
        [-0.6518,  0.8798, -0.8236,  0.1086,  0.1859]])

In [107]:
unsqueezed_weights = weights.unsqueeze(0).unsqueeze_(1)
unsqueezed_batch_t = batch_t.unsqueeze(1)
print(batch_t.size())
unsqueezed_batch_t.size()
unsqueezed_batch_t

torch.Size([2, 3, 5, 5])


tensor([[[[[-0.2522, -0.5465, -1.0661, -0.2703,  0.2912],
           [-1.9194,  0.6558, -0.4081, -0.8264, -0.8559],
           [ 0.5533,  0.3027, -0.2299,  0.3027,  0.4724],
           [-0.5589, -0.3083,  0.6340,  1.3137, -0.2567],
           [ 0.9770,  0.1861,  0.1670, -0.4332, -1.7593]],

          [[ 0.8892, -1.5584,  1.7762,  1.1250,  0.9167],
           [-0.2574,  2.0215, -1.4506, -1.5133,  1.1040],
           [-1.4660,  1.1427,  0.0780,  1.4443, -0.2254],
           [ 1.3790,  0.6935,  0.7775,  0.7608,  1.2757],
           [ 1.2280,  1.6489, -0.3250, -2.9801,  0.6217]],

          [[ 0.7542,  0.0473,  1.4862, -0.9190,  0.6266],
           [ 0.4374, -0.0491, -0.6902,  0.4553,  1.7174],
           [-2.6700,  0.1640, -0.3968, -0.1187, -0.7723],
           [ 0.1353, -0.4946,  0.1478,  0.2152,  0.6907],
           [-0.8084,  1.9641,  1.0960,  0.6123,  1.3975]]]],



        [[[[-0.2968, -0.3184, -0.0831,  0.6939,  2.8530],
           [-0.4354,  0.2734,  0.4533, -0.8902,  0.4136],
    

In [110]:
a = torch.tensor([[1, 2], [3, 4], [5, 6]])
b = torch.tensor([1, 1])
print(a.size(), b.size())
a+b

torch.Size([3, 2]) torch.Size([2])


tensor([[2, 3],
        [4, 5],
        [6, 7]])

In [113]:
a = torch.tensor([[1, 3, 5], [2, 4, 6]])
b = torch.tensor([1, 1])
print(a.size(), b.size())
a+b

torch.Size([2, 3]) torch.Size([2])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [121]:
a = torch.tensor([[1, 3, 5], [2, 4, 6]])
b = torch.tensor([1, 1]).unsqueeze(-1)
print(b)
print(a.size(), b.size())
a+b

tensor([[1],
        [1]])
torch.Size([2, 3]) torch.Size([2, 1])


tensor([[2, 4, 6],
        [3, 5, 7]])

In [ ]:
####