#### 3.2.1 From Python lists to PyTorch tensors

In [1]:
import torch
a = [1.0, 2.0, 1.0]

/home/paul/mambaforge/envs/qtc/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
a[0]
a[2] = 3.0
a[2]
a

[1.0, 2.0, 3.0]

#### Constructing our first tensors

In [3]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [4]:
a[1]

tensor(1.)

In [5]:
float(a[1])

1.0

In [6]:
a[2] = 2.0
a

tensor([1., 1., 2.])

#### 3.2.3 The essence of tensors

In [7]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points


tensor([4., 1., 5., 3., 2., 1.])

In [8]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [9]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [10]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [11]:
points.shape

torch.Size([3, 2])

In [12]:
points = torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [13]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points[0,1]

tensor(1.)

In [14]:
points[0]

tensor([4., 1.])

#### 3.3 Indexing Tensor

In [15]:
some_list = list(range(6))
some_list[:]
some_list[1:4]
some_list[1:]
some_list[:-1]
some_list[1:4:2]

[1, 3]

In [16]:
points[1:]
points[1:,:]
points[1:,0]
points[None] 

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

#### 3.4 Named tensors

In [17]:
img_t = torch.randn(3,5,5) # shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])
img_t

tensor([[[ 0.2355,  1.5252,  0.7080,  0.8861,  0.4358],
         [ 1.2270,  0.0955, -0.7707, -0.5155, -0.1743],
         [ 0.4138,  0.0450,  0.3627,  2.0956,  1.2593],
         [ 1.0575, -0.5783, -0.0779,  0.9399, -0.6592],
         [-0.5338, -0.6734, -3.2159, -1.9171, -0.4401]],

        [[-1.2042, -0.7688,  2.2852, -0.8033,  2.4653],
         [-0.1758, -0.2488,  0.0965,  1.0860,  0.3345],
         [-1.0208,  0.9926,  2.2634, -0.3904,  0.1316],
         [ 1.3155,  0.7323, -1.5659,  0.9759, -2.4190],
         [-0.2861,  0.2329,  0.4683,  2.1609, -0.2857]],

        [[-0.6034, -0.8661, -0.8436,  0.1438,  0.3404],
         [ 1.7107,  0.1020,  0.6593, -0.3106, -1.0797],
         [ 1.2496, -1.7264,  1.0674, -1.8556, -0.2243],
         [ 0.3937, -0.5392, -0.0927,  0.1176,  0.8359],
         [-0.7907, -0.6690, -0.0174, -1.0677, -0.5199]]])

In [18]:
batch_t = torch.randn(2, 3, 5, 5)

In [19]:
img_gray_naive = img_t.mean(-3) # ()안에 숫자는 .size()의 Index위치를 나타냄. negative indexing이 가능함. 보통은 -1만 씀.
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [20]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t*unsqueezed_weights)
batch_weights = (batch_t*unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
print(img_t.shape, weights.shape, unsqueezed_weights.shape)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape, img_weights.shape

torch.Size([3, 5, 5]) torch.Size([3]) torch.Size([3, 1, 1])


(torch.Size([2, 3, 5, 5]),
 torch.Size([2, 3, 5, 5]),
 torch.Size([3, 1, 1]),
 torch.Size([3, 5, 5]))

#### unsqueeze example

In [21]:
a = torch.tensor([[1, 2], [3, 4], [5, 6]])
b = torch.tensor([1, 1])
print(a.size(), b.size())
a+b

torch.Size([3, 2]) torch.Size([2])


tensor([[2, 3],
        [4, 5],
        [6, 7]])

In [22]:
a = torch.tensor([[1, 3, 5], [2, 4, 6]])
b = torch.tensor([1, 1])
print(a.size(), b.size())
a+b

torch.Size([2, 3]) torch.Size([2])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [ ]:
a = torch.tensor([[1, 3, 5], [2, 4, 6]])
b = torch.tensor([1, 1]).unsqueeze(-1)
print(b)
print(a.size(), b.size())
a+b

tensor([[1],
        [1]])
torch.Size([2, 3]) torch.Size([2, 1])


tensor([[2, 4, 6],
        [3, 5, 7]])

In [ ]:
print(img_t.shape, weights.shape, batch_t.shape)
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
batch_t, weights, batch_gray_weighted_fancy

torch.Size([3, 5, 5]) torch.Size([3]) torch.Size([2, 3, 5, 5])


(tensor([[[[ 0.3845, -1.1025,  0.5564,  0.5431, -0.1063],
           [-0.6325,  0.4164, -0.4063,  0.4241,  0.7437],
           [ 0.0489, -0.7385,  1.4587,  0.7679,  1.0362],
           [-0.1793, -1.9656,  0.1711,  1.8167,  0.4754],
           [ 1.3298, -0.5517, -1.0594, -1.4008, -1.1963]],
 
          [[-1.0382, -1.3235,  0.6334,  0.0487, -1.4143],
           [ 1.4939,  0.1094, -0.3771,  1.0141, -0.2653],
           [-0.8385, -2.7776,  0.3090,  0.5571, -1.1236],
           [ 1.1892,  1.1327, -1.3428,  0.7328, -0.1831],
           [-1.6401, -1.0479, -0.4189, -1.4258,  0.7155]],
 
          [[-1.5731, -0.7965,  1.5081,  0.1891, -1.4752],
           [-0.2894, -0.2603, -0.3767, -0.6214, -0.7118],
           [ 0.7494,  0.4127, -1.6566,  0.0103,  0.0305],
           [-0.3892,  0.0955,  0.7855, -0.6072,  0.7304],
           [-1.4054, -1.0455, -2.1222, -0.7565,  0.3038]]],
 
 
         [[[-2.7866,  0.9065,  0.8948,  0.2816,  1.3638],
           [-1.7164,  1.7750, -0.0635,  0.4487, -0.7344],
  

In [ ]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [ ]:
img_named = img_t.refine_names(...,'channels','rows','column')
batch_named = batch_t.refine_names(...,'channels','rows','column')
print("img named: ", img_named.shape, img_named.names)
print("batch named: ", batch_named.shape, batch_named.names)

img named:  torch.Size([3, 5, 5]) ('channels', 'rows', 'column')
batch named:  torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'column')


In [ ]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'column'))

In [ ]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'column'))

In [ ]:
gray_named = (img_named[..., :3]*weights_named).sum('channels')

RuntimeError: Error when attempting to broadcast dims ['channels', 'rows', 'column'] and dims ['channels']: dim 'column' and dim 'channels' are at the same position from the right but do not match.

In [ ]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

#### 3.5.3 Managing a tensor's dtype attribute

In [ ]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [ ]:
short_points.dtype

torch.int16

In [ ]:
double_points = torch.zeros(10,2).double()
short_points = torch.ones(10,2).short()

In [ ]:
double_points = torch.zeros(10,2).to(torch.double)
short_points = torch.ones(10,2).to(dtype=torch.short)

In [ ]:
points_64 = torch.rand(5, dtype=torch.double)
points_short = points_64.to(torch.short)
points_64 * points_short # works form PyTorch 1.3 onwards

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

#### 3.6 The tensor API

In [ ]:
a = torch.ones(3,2)
a_t = torch.transpose(a, 0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [ ]:
a = torch.ones(3,2)
a_t = a.transpose(0,1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

#### 3.7.1 Indexing into storage

In [ ]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [ ]:
points_storage = points.storage()
points_storage[0]

4.0

In [ ]:
points.storage()[1]

1.0

In [ ]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

#### 3.7.2 Modifying stored values : In-place operations

In [ ]:
a = torch.ones(3,2)
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

#### 3.8 Tensor metadata : Size, offset, and stride

#### 3.8.1 Views of another tensor's storage

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1] # points.storage를 그대로 가져와서 offset이 바뀜
second_point.storage_offset()

2

In [ ]:
second_point.size()

torch.Size([2])

In [ ]:
second_point.shape

torch.Size([2])

In [ ]:
points.stride()

(2, 1)

In [ ]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [ ]:
second_point.storage_offset()

2

In [ ]:
second_point.stride()

(1,)

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1] # points.storage를 그대로 가져와서 offset이 바뀜
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

#### 3.8.2 Transposing without copying

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [ ]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [ ]:
id(points.storage()) == id(points_t.storage())

True

In [ ]:
points.stride()

(2, 1)

In [ ]:
points_t.stride()

(1, 2)

#### 3.8.3 Transposing in higher dimensions

In [ ]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [ ]:
transpose_t.shape

torch.Size([5, 4, 3])

In [ ]:
some_t.stride()

(20, 5, 1)

In [ ]:
transpose_t.stride()

(1, 5, 20)

#### 3.8.4 Contiguous tensors

In [ ]:
points.is_contiguous()

True

In [ ]:
points_t.is_contiguous()

False

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [ ]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [ ]:
points_t.stride()

(1, 2)

In [ ]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [ ]:
points_t_cont.stride()

(3, 1)

In [ ]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

#### 3.9 Moving tensors to the GPU

#### 3.9.1 Managing a tensor's device attribute

In [23]:
points_gpu = torch.tensor([[4.0, 1.0],[5.0, 3.0],[2.0, 1.0]], device='cuda') # mac에는 cuda가 없어서 일단 'Cpu'로 함

In [24]:
points_gpu = points.to(device='cuda')

In [25]:
points_gpu = points.to(device='cuda:0') # 0번 cpu에 연산을 할당한다는 의미

In [26]:
points = 2*points
points_gpu = 2*points.to(device='cuda')

In [27]:
points_gpu = points_gpu + 4


In [28]:
points_cpu = points_gpu.to(device='cpu')

In [29]:
points_gpu = points.cuda() # Defaults to GPU index 0
points_gpu = points.cuda(0)
points_cpu =- points_gpu.cpu()

#### 3.10 NumPy interoperability

In [30]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [31]:
points = torch.from_numpy(points_np) # numpy -> torch tensor

#### 3.11 Generalized tensors are tensors, too

#### 3.12 Serializing tensors

In [32]:
torch.save(points, '../Desktop.t')

In [33]:
with open('../Desktop.t','wb') as f:
    torch.save(points,f)

In [34]:
points = torch.load('../Desktop.t')

In [35]:
with open('../Desktop.t','rb') as f:
    points = torch.load(f)

#### 3.12.1 Serializing to HDF5 with h5py

In [36]:
import h5py

f = h5py.File('../Desktop.hdf5','w')
dset = f.create_dataset('coords', data = points.numpy())
f.close()

ModuleNotFoundError: No module named 'h5py'

In [37]:
f = h5py.File('../Desktop.hdf5','r')
dset = f['coords']
last_points = dset[-2:]

NameError: name 'h5py' is not defined

In [38]:
last_pointsa = torch.from_numpy(dset[-2:])
f.close()

NameError: name 'dset' is not defined

#### 3.14 Exercises

In [39]:
# 1
a = torch.tensor((range(9)))
a.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9]

In [40]:
b = a.view(3,3)
b.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9]

In [41]:
c = b[1:,1:]
c

tensor([[4, 5],
        [7, 8]])

In [42]:
# 2


NameError: name 'ß' is not defined