In [1]:
# Lab-01-1 Tensor Manipulation 1
import numpy as np
import torch

/Users/paul/opt/miniconda3/envs/qtc/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank of t:', t.ndim)
print('Shape of t:', t.shape)

Rank of t: 1
Shape of t: (7,)


In [5]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # Element
print('[t[2:5] t[4:-1] = ', t[2:5], [t[4:-1]]) # Slicing
print('t[:2] t[3:] = ', t[:2], t[3:]) # Slicing

t[0] t[1] t[-1] =  0.0 1.0 6.0
[t[2:5] t[4:-1] =  [2. 3. 4.] [array([4., 5.])]
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


In [7]:
t = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9],[10.,11.,12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [8]:
print('Rank fo t: ', t.ndim)
print('Shape of t : ', t.shape)

Rank fo t:  2
Shape of t :  (4, 3)


In [10]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [11]:
print(t.dim()) # rank
print(t.shape) # shape
print(t.size()) # shape
print(t[0],t[1],t[-1]) # Element
print(t[2:5],t[4:-1]) # Slicing
print(t[:2],t[3:])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [21]:
t = torch.FloatTensor([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]]) 
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [22]:
print(t.dim()) # rank
print(t.size()) # shape
print(t[:, 1])
print(t[:,1].size())
print(t[:,:-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [23]:
# Same shape
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1 + m2)

tensor([[5., 5.]])


In [29]:
# Vector + scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3]) # [3] -> [[3,3]]
print(m1+m2)

torch.Size([1, 2])
tensor([[4., 5.]])


In [30]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])
