In [3]:
# Lab-01-1 Tensor Manipulation 1
import numpy as np
import torch

/Users/paul/opt/miniconda3/envs/qtc/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [5]:
print('Rank of t:', t.ndim)
print('Shape of t:', t.shape)

Rank of t: 1
Shape of t: (7,)


In [6]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # Element
print('[t[2:5] t[4:-1] = ', t[2:5], [t[4:-1]]) # Slicing
print('t[:2] t[3:] = ', t[:2], t[3:]) # Slicing

t[0] t[1] t[-1] =  0.0 1.0 6.0
[t[2:5] t[4:-1] =  [2. 3. 4.] [array([4., 5.])]
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


In [7]:
t = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9],[10.,11.,12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [8]:
print('Rank fo t: ', t.ndim)
print('Shape of t : ', t.shape)

Rank fo t:  2
Shape of t :  (4, 3)


In [9]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [10]:
print(t.dim()) # rank
print(t.shape) # shape
print(t.size()) # shape
print(t[0],t[1],t[-1]) # Element
print(t[2:5],t[4:-1]) # Slicing
print(t[:2],t[3:])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [11]:
t = torch.FloatTensor([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]]) 
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [12]:
print(t.dim()) # rank
print(t.size()) # shape
print(t[:, 1])
print(t[:,1].size())
print(t[:,:-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [13]:
# Same shape
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1 + m2)

tensor([[5., 5.]])


In [14]:
# Vector + scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3]) # [3] -> [[3,3]]
print(m1+m2)

tensor([[4., 5.]])


In [15]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


In [17]:
print()
print('------------------------')
print('Mul VS Matumul')
print('------------------------')
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1 : ', m1.shape) # 2 x 2
print('Shape of Matrix 2 : ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1 : ', m1.shape) # 2 x 2
print('Shape of Matrix 2 : ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 1


------------------------
Mul VS Matumul
------------------------
Shape of Matrix 1 :  torch.Size([2, 2])
Shape of Matrix 2 :  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1 :  torch.Size([2, 2])
Shape of Matrix 2 :  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])


In [18]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [20]:
# Can't use mean() on integers
t = torch.LongTensor([1,2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)


mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [22]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [24]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [25]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [27]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [28]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [29]:
print(t.max())

tensor(4.)


In [31]:
print(t.max(dim=0))
print('Max : ', t.max(dim=0)[0])
print('Argmax : ', t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max :  tensor([3., 4.])
Argmax :  tensor([1, 1])


In [32]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
